type Customer {
  id: ID
  firstName: String
  lastName: String
  company: String
  email: String
  phone: String
  userId: ID
}

type TopCustomer {
  total: Float
  customer: Customer
}

input CustomerCreateInput {
  firstName: String!
  lastName: String!
  company: String!
  email: String!
  phone: String
}

input CustomerUpdateInput {
  firstName: String
  lastName: String
  company: String
  email: String
  phone: String
}

type Query {
  getCustomers: [Customer]
  getCustomersBySeller: [Customer]
  getCustomer(id: ID!): Customer
  getBestCustomers: [TopCustomer]
}

type Mutation {
  createCustomer(input: CustomerCreateInput): Customer
  updateCustomer(id: ID!, input: CustomerUpdateInput): Customer
  deleteCustomer(id: ID!): Customer
}